spring:
    data:
        cassandra:
            contact-points: esbqadse1.genpt.net,esbqadse2.genpt.net,esbqadse3.genpt.net
            username: abi_kunkle
            password: YvTR3uXLjNzYtj9R
            port: 9042
            local-datacenter: Atlanta
            keyspace: nsight
            request:
                consistency: local_quorum
                timeout: 10s
            keyspace-name: nsight